export {default as Services} from './services/Services'
export {default as Footer} from './footer/Footer'
export {default as Header} from './header/Header'
export {default as WhyUs} from './whyUs/WhyUs'
export {default as Amenities} from './amenities/Amenities'
export {default as SignUp} from './signUp/SignUp'
export {default as SignIn} from './signUp/SignIn'